frase_input = str(input("La frase para invertir: "))
frase_list = frase_input.split()
print(frase_list)
frase_list_reversed = frase_list.reverse()
print(frase_list_reversed)
frase_output = ' '.join(frase_list)
print(frase_output)